# Generated by Django 4.1.7 on 2023-03-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_student_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_feedback',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_feedback',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
